version: '3'

volumes:
  db-data:

services:
  db:
    image: postgres:10.5
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
    volumes:
      - 'db-data:/var/lib/postgresql/data'

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      SELENIUM_DRIVER_URL: http://selenium_chrome:4444/wd/hub
    volumes:
      - '.:/rails_practice_book'
    tty: true
    stdin_open: true
    depends_on:
      - db
      - selenium_chrome

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none

  smtp:
    image: schickling/mailcatcher
    container_name: mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"